carce:
  prefix: https://testcloud.carce.cc
  carbuy-prefix: https://carbuy.com.tw
  webUrl: https://sale.carce.cc
  ftp:
    server: testcloud.carce.cc
    port: 21
    user: testcloud
    password: x32*9oFb6
ruoyi:
  profile: /root/files
spring:
  datasource:
    carcecloud:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3306/test_carce_cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: test_cloud
      password: "oP9m7_2h"
    manager:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3306/carbuy_cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: carbuy_cloud
      password: "L2k~5HR?v9wewdgl"

# 绿界支付配置
ecpay:
  # 测试环境配置
  production: true
  merchant-id: "3014517"  # 商户编号
  hash-key: "lGOh0vxYukFihTZX"  # HashKey
  hash-iv: "pWlpnfGdkQYuKkBQ"   # ashIV
  return-url: "https://carbuy.com.tw/ecpay/return"
  notify-url: "https://carbuy.com.tw/ecpay/callback"
  client-back-url: "https://carbuy.com.tw/my-order/detail-page?orderId="
  result-url: "https://carbuy.com.tw/ecpay/result"
  # 查询API地址配置
  query-server-url: "https://payment.ecpay.com.tw/Cashier/QueryTradeInfo/V5"
  # 物流API地址配置
  logistics-api-url: "https://logistics-stage.ecpay.com.tw"
  logistics-production-url: "https://logistics.ecpay.com.tw"
