carce:
  prefix: https://testcloud.carce.cc
  carbuy-prefix: https://carbuy.com.tw
  webUrl: http://localhost:8080
  ftp:
    server: testcloud.carce.cc
    port: 21
    user: testcloud
    password: x32*9oFb6
spring:
  datasource:
    carcecloud:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.mariadb.jdbc.Driver
#      url: jdbc:mariadb://47.239.20.245:4416/carce_cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&connectTimeout=30000&socketTimeout=60000&autoReconnect=true&failOverReadOnly=false
      url: jdbc:mariadb://localhost:3316/carce_cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&connectTimeout=30000&socketTimeout=60000&autoReconnect=true&failOverReadOnly=false
      username: root
      password: "123456"
      # Druid连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      # 连接超时配置
#      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;druid.stat.logSlowSql=true;druid.connectionTimeout=30000;druid.validationQueryTimeout=10000
    manager:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.mariadb.jdbc.Driver
#      url: jdbc:mariadb://47.239.20.245:4416/ruoyi_car?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&connectTimeout=30000&socketTimeout=60000&autoReconnect=true&failOverReadOnly=false
      url: jdbc:mariadb://localhost:3316/ruoyi_car?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&connectTimeout=30000&socketTimeout=60000&autoReconnect=true&failOverReadOnly=false
      username: root
      password: "123456"
      # Druid连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      # 连接超时配置
#      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;druid.stat.logSlowSql=true;druid.connectionTimeout=30000;druid.validationQueryTimeout=10000
  freemarker:
   cache: false
   settings:
     template_update_delay: 0
  devtools:
    restart:
      exclude: static/**,public/**,resources/**,META-INF/**,templates/**

# 绿界支付配置
ecpay:
  # 测试环境配置
  production: false
  merchant-id: "3002607"  # 官方测试商户编号
  hash-key: "pwFHCqoQZGmho4w6"  # 官方测试HashKey
  hash-iv: "EkRm7iFT261dpevs"   # 官方测试HashIV
  return-url: "http://localhost:8080/api/payment/return"
  notify-url: "http://localhost:8080/api/payment/callback"
  client-back-url: "https://carce.yanjiashuo.cn/my-order/detail-page?orderId="
  result-url: "http://localhost:8080/payment/result"
  # 查询API地址配置
  query-server-url: "https://payment-stage.ecpay.com.tw/Cashier/QueryTradeInfo/V5"
  # 物流API地址配置
  logistics-api-url: "https://logistics-stage.ecpay.com.tw"
  logistics-production-url: "https://logistics.ecpay.com.tw"
